import {ReactComponent as Facebook} from './facebook.svg'
import {ReactComponent as Instagram} from './instagram-216-721958.svg'
import {ReactComponent as Twitter} from './twitter-241-721979.svg'
import {ReactComponent as Heart} from './heart.svg'
import {ReactComponent as RatingStar} from './Star 2.svg'
import {ReactComponent as MetaLogo} from './meta-logo.svg'
import {ReactComponent as OpenSeaLogo } from './openSea_logo.svg'
import {ReactComponent as MbLogo } from './mb-logo.svg'
import {ReactComponent as Opensea } from './opensea.svg'
import {ReactComponent as MetaMask } from './metamask-2.svg'
import {ReactComponent as MbToken } from './mb-token.svg'
import {ReactComponent as MetamaskIcon } from './metamask.svg'
import {ReactComponent as RightIcon } from './right-icon.svg'
import {ReactComponent as TimesIcon } from './times.svg'
import {ReactComponent as WalletICon } from './wallet.svg'

export {Facebook, Instagram, Twitter, Heart, RatingStar, OpenSeaLogo, MbLogo, MetaLogo, Opensea, MetaMask, MbToken, MetamaskIcon, WalletICon, RightIcon, TimesIcon}