import FooterLogo from './footer_logo.png'
import MainLogo from './Logo.png'
import MobLogo from './mobile-logo.png'
import MobFooterLogo from './mobile-footer-logo.png'
import HeroImg from './hero-img.png'
import NftSec from './Frame 59546.png'
import Place01 from './place-1.png'
import Place02 from './place-2.png'
import Place03 from './place-3.png'
import Place04 from './place-4.png'
import Place05 from './place-5.png'
import Place06 from './place-6.png'
import Place07 from './place-7.png'
import Place08 from './place-8.png'
import Place09 from './place-9.png'
import Place10 from './place-10.png'
import Place11 from './place-11.png'
import Place12 from './place-12.png'
import Place13 from './place-13.png'
import Place14 from './place-14.png'
import Place15 from './place-15.png'
import Place16 from './place-16.png'

export  {FooterLogo, MainLogo, MobFooterLogo, MobLogo, HeroImg, NftSec, Place01, Place02, Place03, Place04, Place05, Place06, Place07, Place08, Place09, Place10, Place11, Place12, Place13, Place14, Place15, Place16}